### ISSUE TITLE
Move from unicorn to puma with phased start as default

### ISSUE THREAD

**Issue by vipulnsward** [bigbinary/boxy#11]

**Comment by neerajdotname** [comment]
We deployed granary with nginx + puma. If it behaves ok then we will do same in production. Once that is running stable in production then we will use that template as default for newer applications. 

No need to have this as open issue for that to happen though.

**Comment by RahulMahale** [comment]
nginx + puma is running in granary and so for looks good, I think we should consider adding puma template in boxy.

**Comment by neerajdotname** [comment]
@RahulMahale _a sure go ahead.
