### ISSUE TITLE
monit should ping to slack before giving up on DJ

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/boxy#19]
In one of the projects soon we are going to have large number of 100+ DJ instances. Sometimes monit gives up on a DJ instance and we are not notified of it. Because of DJ dying now that client does not get any background job processing done.

Any time monit gives up on any process monit should ping on slack.

//cc @ershad @vipulnsward @rkr090 

@RahulMahale _a

**Comment by neerajdotname** [comment]
Bumped up the priority. We need a solution in 1 to 2 weeks.

**Comment by RahulMahale** [comment]
@ershad Where are we with this ?

**Comment by ershad** [comment]
@RahulMahale I moved to other priority issues in between. Would you like to take this up? cc: @neerajdotname

**Comment by RahulMahale** [comment]
@ershad I can pick it up, will look into it

**Comment by RahulMahale** [comment]
@neerajdotname @ershad I need slack channel webhook to test monit alerts, is it ok if I use  existing webhook from #internal-project Channel ?

**Comment by neerajdotname** [comment]
@RahulMahale sure

**Comment by ershad** [comment]
@RahulMahale _a this is already implemented, right? If yes, please close this issue.

**Comment by RahulMahale** [comment]
Yes this feature has been pushed in https://github.com/bigbinary/boxy-rails/pull/22
