### ISSUE TITLE
Issue with /tmp creation

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/boxy#2]
http://take.ms/lz3MHM
/tmp creation has been stuck for 10-15 minutes. Not sure what the issue is. This has been happening consistently now.

**Comment by ershad** [comment]
@RahulMahale did you have this problem any time recently? I don't remember this happening when I used boxy last time.

**Comment by RahulMahale** [comment]
No I too didn't came across such error recently, we can close this for now
