### ISSUE TITLE
Best way to know which version is currently deployed in production or staging

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/boxy#21]
Usually we merge code to production or staging and we deploy. However it does not always mean that the current production branch is the one that is actually running in production.

Sometimes we need to find out which is the last commit that is running in production/staging. We do write after deloyment to revision.log. Let's look into to see what is the best way for one to find out which commit is running in production/staging and accordingly update how-to.md doc.

@RahulMahale _a please look into it.

//cc @ershad

**Comment by RahulMahale** [comment]
@neerajdotname for this change, It was pushed here https://github.com/bigbinary/boxy-cap/pull/13 

how-to is also updated.

by default we have provision to see the latest deployed commit using

 ```  bundle exec cap innovista-staging deploy:log_revision ```
