### ISSUE TITLE
Look into using capistrano_deploy_lock

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/boxy#27]
http://www.caregeneralhelp.com/categories/16/questions/128

**Comment by RahulMahale** [comment]
@neerajdotname ok will add this in our boxy-cap, BTW I didnt get with above mentioned link
it just shows me something like this 
![deplo-lock](https://cloud.githubusercontent.com/assets/1124617/14594653/32673fc0-0556-11e6-91ca-441f26fe3280.png)

**Comment by RahulMahale** [comment]
Tried to setup ` capistrano_deploy_lock `  but looks like it doesn't supports Capistrano 3, there is already an ticket for it https://github.com/ndbroadbent/capistrano_deploy_lock/issues/7

**Comment by neerajdotname** [comment]
That's wrong url I posted. I will close this issue and will open a new one.
