### ISSUE TITLE
Rails logs to syslog 

### ISSUE THREAD

**Issue by RahulMahale** [bigbinary/boxy#29]

**Comment by RahulMahale** [comment]
Will start working  on it once we confirm uniform approach here https://github.com/bigbinary/bigbinary-website/pull/386

**Comment by neerajdotname** [comment]
Who needs to confirm.

**Comment by RahulMahale** [comment]
Waiting for Vipul and Ershad's thoughts on https://github.com/bigbinary/bigbinary-website/pull/386
As per your comment once they approve it there that will be same everywhere.

**Comment by RahulMahale** [comment]
Closing! As we decided not to send logs to syslog.
