### ISSUE TITLE
Investigate and add pg/mysql password configuration from node config.

### ISSUE THREAD

**Issue by vipulnsward** [bigbinary/boxy#4]
Right now, it defaults to one shipped by the chef packages.

**Comment by vipulnsward** [comment]
@RahulMahale @ershad please investigate this when you get time.

**Comment by RahulMahale** [comment]
@ershad  where can I find chef cookbooks of postgres and mysql cookbook for boxy so that I can check the recipes of the same.

**Comment by ershad** [comment]
@RahulMahale Please check `Berksfile` -  https://github.com/bigbinary/boxy/blob/master/Berksfile#L23

**Comment by neerajdotname** [comment]
Closing it since most of our projects use pg and even if it is an issue it can be manually fixed.
