### ISSUE TITLE
Ruby Version mismatch

### ISSUE THREAD

**Issue by RahulMahale** [bigbinary/boxy#8]
while deplpoying the bigwheel app using boxy using capistrano it threw ruby version error 
`DEBUG [251e5020] 	Your Ruby version is 2.2.2, but your Gemfile specified 2.2.3
`

when I checked the gemfile the project boxy uses the ruby 2.2.2 and project wheel uses ruby 2.2.3.

the complete log output is here https://gist.github.com/RahulMahale/2af98990c52fcf740ade

cc @vipulnsward @ershad

**Comment by vipulnsward** [comment]
This is because, you provisioned the machine with ruby 2.2.2(https://github.com/bigbinary/boxy/blob/master/nodes/example.json#L3), 
and the application Gemfile has ruby 2.2.3. 
re-provision the box with ruby 2.2.3.
